apiVersion: v1
entries:
  redis:
  - annotations:
      category: Database
      images: |
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.32.3-debian-12-r1
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r40
        - name: redis
          image: docker.io/bitnami/redis:7.4.2-debian-12-r6
        - name: redis-exporter
          image: docker.io/bitnami/redis-exporter:1.69.0-debian-12-r1
        - name: redis-sentinel
          image: docker.io/bitnami/redis-sentinel:7.4.2-debian-12-r6
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 7.4.2
    created: "2025-04-21T06:08:40.460070619Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: b164ab538268fc28a68456e712d296705443962747fc8bcf97c4ab5022048f84
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - https://vigneshpandian.github.io/helmrepo/charts/redis-20.11.5.tgz
    version: 20.11.5
generated: "2025-04-21T06:08:40.450839112Z"
