apiVersion: v1
kind: Secret
metadata:
  name: redis-connection-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  redisConnectionString: {{ .Values.redis.connectionString | b64enc | quote }}