apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-secret-reader-binding
  labels:
    app: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: redis-user
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: redis-secret-reader
  apiGroup: rbac.authorization.k8s.io