apiVersion: v1
kind: Secret
metadata:
  name: redis-connection-secret
  labels:
    {{- include "redis-api-demo.labels" . | nindent 4 }}
type: Opaque
data:
  redisConnectionString: {{ .Values.redis.connectionString | b64enc | quote }}